api/urls.py
from rest_framework.routers import DefaultRouter
from .views import (
    OrganizationViewSet,
    EventView,
    ApplicationView,
    SpiritualRestView,
    AccidentsView
)
from django.urls import path, include
from api import views

router = DefaultRouter()
router.register(r'organizations', OrganizationViewSet)
router.register(r'spirtual-rest', SpiritualRestView)
router.register(r'accident', AccidentsView)


urlpatterns = [
    path("singup/", views.UserRegisterAPIView.as_view(), name="signup"),
    path("login/", views.UserLoginAPIView.as_view(), name="login"),
    path("profile/", views.UserProfileAPIView.as_view(), name="profile"),
    path("logout/", views.UserLogoutAPIView.as_view(), name="logout"),
    path('', include(router.urls)),
    path('event/', EventView.as_view()),
    path('event/<int:id>/', EventView.as_view()),
    path('application/', ApplicationView.as_view()),
    path('application/<int:id>/', ApplicationView.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
    openapi.Info(
        title="Trade Union System API",
        default_version='v1',
        description="API for Trade Union System of Alfraganus University",
        terms_of_service="https://afu.uz/",
        contact=openapi.Contact(email="sodiqdevpython@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('swagger/', schema_view.with_ui('swagger',cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',cache_timeout=0), name='schema-redoc'),
    path('api/v1/', include('api.urls')),
    path('', include('organization.urls')),
    path('employee/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import FileExtensionValidator, MaxValueValidator
from users import managers, choices
from utils.models import BaseModel


class User(AbstractBaseUser, PermissionsMixin):
    # full_name = models.CharField(max_length=256)
    id_card = models.CharField(max_length=9, unique=True)
    # phone_number = models.CharField(max_length=13, unique=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_joined = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "id_card"


    objects = managers.UserManager()

    def __str__(self):
        return self.id_card

class UserExtraData(BaseModel):
    user = models.OneToOneField(
        "User",
        on_delete=models.SET_NULL,
        null=True,
        related_name='user_data'
    )

    name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    father_name = models.CharField(max_length=64)
    phone_number = models.CharField(max_length=13, unique=True)
    profile_image = models.ImageField(
        upload_to='userExtradata/',
        null=True, blank=True,
        validators=[
            FileExtensionValidator(
                allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'avif'],
                message="Faqat rasm yuklashingiz mumkin (png, jpg, jpeg, webp, avif) formatlarida"
            )
        ]
    )
    under_age_children_number = models.SmallIntegerField(
        default = 0,
        validators = [MaxValueValidator(6,message="Faqat 18 yoshga yetmagan bolalaringiz soni kerak !")]
    )
    adress = models.TextField()
    born_in = models.DateField()
    employment_at = models.DateField()
    job = models.ForeignKey('Job', on_delete=models.SET_NULL, null=True, blank=True)
    salary = models.DecimalField(
        max_digits=16, decimal_places=2
    )
    score = models.SmallIntegerField(default=0)
    allocated_funds = models.PositiveIntegerField(default=0) # qancha pul ajratildi ushbu user uchun organization dan

    def __str__(self) -> str:
        return f"{self.name}|{self.last_name}"
    
    class Meta:
        verbose_name = "Ishchi qo'shimcha ma'lumoti"
        verbose_name_plural = "Ishchilarning qo'shimcha ma'lumotlari"
    

class UnderAgeChildren(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to='under_age_children/')
    child_full_name = models.CharField(max_length=128)

    def __str__(self):
        return f"Voyaga yetmagan farzand hujjati - {self.id}"

    class Meta:
        verbose_name = "Voyaga yetmagan farzand hujjati"
        verbose_name_plural = "Voyaga yetmagan farzandlar hujjatlari"


class HandicappedDocsModel(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to='handicapped/')
    type = models.CharField(
        max_length=1,
        choices=choices.HandicappedType.choices,
        default=choices.HandicappedType.is_valid
    )

    def __str__(self):
        return f"Nogironlik hujjati - {self.id}"

    class Meta:
        verbose_name = "Nogironlik haqidagi hujjat"
        verbose_name_plural = "Nogironlik haqidagi hujjatlar"


class RoleNoteModel(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to='docs/role/')
    type = models.CharField(
        max_length=1,
        choices=choices.RoleNote.choices,
        default=choices.RoleNote.is_inactive
    )

    def __str__(self):
        return f"Daftar - {self.id}"

    class Meta:
        verbose_name = "Daftar"
        verbose_name_plural = "Daftarlar"


class Job(BaseModel):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Ish turi"
        verbose_name_plural = "Ish turlari"

templates/add_event.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'create_event' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Tadbir nomi</label>
            <input name="title" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Tadbir nomi" required>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Ajratilishi kerak bo'lgan mablag'</label>
            <input name="spend_money" type="number" class="form-control" id="exampleFormControlInput1" placeholder="Mablag' sumda" required>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Ko'proq ma'lumot</label>
            <textarea name="description" class="form-control" id="exampleFormControlTextarea1" rows="12" required></textarea>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Rasm</label>
            <input max="10" name="image" class="form-control" type="file" required>
        </div>
        <input type="submit" value="Yaratish" class="btn btn-success">
    </form>
</div>
{% endblock content %}

templates/billing.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-lg-8">
          <div class="row">
            <div class="col-xl-6 mb-xl-0 mb-4">
              <div class="card bg-transparent shadow-xl">
                <div class="overflow-hidden position-relative border-radius-xl" style="background-image: url('{% static 'img/curved-images/curved14.jpg' %}');">
                  <span class="mask bg-gradient-dark"></span>
                  <div class="card-body position-relative z-index-1 p-3">
                    <i class="fas fa-wifi text-white p-2"></i>
                    <h5 class="text-white mt-4 mb-5 pb-2">4562&nbsp;&nbsp;&nbsp;1122&nbsp;&nbsp;&nbsp;4594&nbsp;&nbsp;&nbsp;7852</h5>
                    <div class="d-flex">
                      <div class="d-flex">
                        <div class="me-4">
                          <p class="text-white text-sm opacity-8 mb-0">Karta egasi</p>
                          <h6 class="text-white mb-0">Sodiq Oydinov</h6>
                        </div>
                        <div>
                          <p class="text-white text-sm opacity-8 mb-0">Muddat</p>
                          <h6 class="text-white mb-0">11/22</h6>
                        </div>
                      </div>
                      <div class="ms-auto w-20 d-flex align-items-end justify-content-end">
                        <img class="w-60 mt-2" src="{% static 'img/logos/mastercard.png' %}" alt="logo">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-6">
              <div class="row">
                <div class="col-md-6">
                  <div class="card">
                    <div class="card-header mx-4 p-3 text-center">
                      <div class="icon icon-shape icon-lg bg-gradient-primary shadow text-center border-radius-lg">
                        <i class="fas fa-landmark opacity-10"></i>
                      </div>
                    </div>
                    <div class="card-body pt-0 p-3 text-center">
                      <h6 class="text-center mb-0">Alfraganus</h6>
                      <span class="text-xs"></span>
                      <hr class="horizontal dark my-3">
                      <h5 class="mb-0">{{ money }} sum</h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-12 mb-lg-0 mb-4">
              <div class="card mt-4">
                <div class="card-header pb-0 p-3">
                  <div class="row">
                    <div class="col-6 d-flex align-items-center">
                      <h6 class="mb-0">Oxirgi o'tkazilgan kartalar</h6>
                    </div>
                    <div class="col-6 text-end">
                      <a class="btn bg-gradient-dark mb-0" href="javascript:;"><i class="fas fa-plus"></i>&nbsp;&nbsp;Yangi karta qo'shish</a>
                    </div>
                  </div>
                </div>
                <div class="card-body p-3">
                  <div class="row">
                    <div class="col-md-6 mb-md-0 mb-4">
                      <div class="card card-body border card-plain border-radius-lg d-flex align-items-center flex-row">
                        <img class="w-10 me-3 mb-0" src="{% static 'img/logos/mastercard.png' %}" alt="logo">
                        <h6 class="mb-0">****&nbsp;&nbsp;&nbsp;****&nbsp;&nbsp;&nbsp;****&nbsp;&nbsp;&nbsp;7852</h6>
                        <i class="fas fa-pencil-alt ms-auto text-dark cursor-pointer" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Card"></i>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="card card-body border card-plain border-radius-lg d-flex align-items-center flex-row">
                        <img class="w-10 me-3 mb-0" src="{% static 'img/logos/visa.png' %}" alt="logo">
                        <h6 class="mb-0">****&nbsp;&nbsp;&nbsp;****&nbsp;&nbsp;&nbsp;****&nbsp;&nbsp;&nbsp;5248</h6>
                        <i class="fas fa-pencil-alt ms-auto text-dark cursor-pointer" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Card"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card h-100">
            <div class="card-header pb-0 p-3">
              <div class="row">
                <div class="col-6 d-flex align-items-center">
                  <h6 class="mb-0">Pul bilan bog'liq invoislar</h6>
                </div>
                <div class="col-6 text-end">
                  <button class="btn btn-outline-primary btn-sm mb-0">Hammasini ko'rish</button>
                </div>
              </div>
            </div>
            <div class="card-body p-3 pb-0">
             <h3>Hali hech qancha ishlatmadingiz</h3>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-7 mt-4">
          <div class="card">
            <div class="card-header pb-0 px-3">
              <h6 class="mb-0">Oxirgi sarf xarajatlar</h6>
            </div>
            <div class="card-body pt-4 p-3">
              <ul class="list-group">
                <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                  <div class="d-flex flex-column">
                    <h6 class="mb-3 text-sm">Sodiq Oydinov ga</h6>
                    <span class="mb-2 text-xs">Ariza yozilgan: <span class="text-dark font-weight-bold ms-sm-2">Sodiq Oydinov</span></span>
                    <span class="mb-2 text-xs">Telefon raqam: <span class="text-dark ms-sm-2 font-weight-bold">+998 99 032 78 98</span></span>
                  </div>
                  <div class="ms-auto text-end">
                    <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="javascript:;"><i class="far fa-trash-alt me-2"></i>O'chirish</a>
                    <a class="btn btn-link text-dark px-3 mb-0" href="javascript:;"><i class="fas fa-pencil-alt text-dark me-2" aria-hidden="true"></i>Tahrirlash</a>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- <div class="col-md-5 mt-4">
          <div class="card h-100 mb-4">
            <div class="card-header pb-0 px-3">
              <div class="row">
                <div class="col-md-6">
                  <h6 class="mb-0">Your Transaction's</h6>
                </div>
                <div class="col-md-6 d-flex justify-content-end align-items-center">
                  <i class="far fa-calendar-alt me-2"></i>
                  <small>23 - 30 March 2020</small>
                </div>
              </div>
            </div>
            <div class="card-body pt-4 p-3">
              <h6 class="text-uppercase text-body text-xs font-weight-bolder mb-3">Newest</h6>
              <ul class="list-group">
                <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                  <div class="d-flex align-items-center">
                    <button class="btn btn-icon-only btn-rounded btn-outline-danger mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-arrow-down"></i></button>
                    <div class="d-flex flex-column">
                      <h6 class="mb-1 text-dark text-sm">Netflix</h6>
                      <span class="text-xs">27 March 2020, at 12:30 PM</span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center text-danger text-gradient text-sm font-weight-bold">
                    - $ 2,500
                  </div>
                </li>
                <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                  <div class="d-flex align-items-center">
                    <button class="btn btn-icon-only btn-rounded btn-outline-success mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-arrow-up"></i></button>
                    <div class="d-flex flex-column">
                      <h6 class="mb-1 text-dark text-sm">Apple</h6>
                      <span class="text-xs">27 March 2020, at 04:30 AM</span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center text-success text-gradient text-sm font-weight-bold">
                    + $ 2,000
                  </div>
                </li>
              </ul>
              <h6 class="text-uppercase text-body text-xs font-weight-bolder my-3">Yesterday</h6>
              <ul class="list-group">
                <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                  <div class="d-flex align-items-center">
                    <button class="btn btn-icon-only btn-rounded btn-outline-success mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-arrow-up"></i></button>
                    <div class="d-flex flex-column">
                      <h6 class="mb-1 text-dark text-sm">Stripe</h6>
                      <span class="text-xs">26 March 2020, at 13:45 PM</span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center text-success text-gradient text-sm font-weight-bold">
                    + $ 750
                  </div>
                </li>
                <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                  <div class="d-flex align-items-center">
                    <button class="btn btn-icon-only btn-rounded btn-outline-success mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-arrow-up"></i></button>
                    <div class="d-flex flex-column">
                      <h6 class="mb-1 text-dark text-sm">HubSpot</h6>
                      <span class="text-xs">26 March 2020, at 12:30 PM</span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center text-success text-gradient text-sm font-weight-bold">
                    + $ 1,000
                  </div>
                </li>
                <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                  <div class="d-flex align-items-center">
                    <button class="btn btn-icon-only btn-rounded btn-outline-success mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-arrow-up"></i></button>
                    <div class="d-flex flex-column">
                      <h6 class="mb-1 text-dark text-sm">Creative Tim</h6>
                      <span class="text-xs">26 March 2020, at 08:30 AM</span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center text-success text-gradient text-sm font-weight-bold">
                    + $ 2,500
                  </div>
                </li>
                <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                  <div class="d-flex align-items-center">
                    <button class="btn btn-icon-only btn-rounded btn-outline-dark mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-exclamation"></i></button>
                    <div class="d-flex flex-column">
                      <h6 class="mb-1 text-dark text-sm">Webflow</h6>
                      <span class="text-xs">26 March 2020, at 05:00 AM</span>
                    </div>
                  </div>
                  <div class="d-flex align-items-center text-dark text-sm font-weight-bold">
                    Pending
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div> -->
      </div>

{% endblock content %}

templates/detail_event.html
{% extends "base.html" %}
{% load template_filters %}

{% block title %}Tadbir{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">{{ data.title }}</h1>
    
    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title">{{ data.title }}</h5>
            <p class="card-text">{{ data.description }}</p>
            <p class="card-text"><strong>Sarflanishi kerak bo'lgan summa:</strong> {{ data.spend_money|display_salary }} sum</p>
            {% if data.image %}
                <img style="width: 100%; max-height: 800px;" src="{{ data.image.url }}" class="img-fluid" alt="{{ data.title }}">
            {% endif %}
        </div>
    </div>

    <div class="card mb-4">
        <div class="card-header">
            Izohlar
        </div>
        <div class="card-body">
            {% if comments %}
                <ul class="list-group list-group-flush">
                    {% for comment in comments %}
                        <li class="list-group-item">
                            <strong>{{ comment.user }}</strong>:
                            {{ comment.text }}
                            <br>
                            <small class="text-muted">{{ comment.created_at }}</small>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p style="color: red;">Hali izohlar yo'q</p>
            {% endif %}
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Izoh qoldirish
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_comment">Izoh</label>
                    <textarea class="form-control" id="id_comment" name="comment" rows="3" required></textarea>
                    <div class="invalid-feedback">Izoh yozish</div>
                </div>
                <button type="submit" class="btn btn-warning">Joylash</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/filling_info.html
{% extends 'base.html' %}

{% block content %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Quyidagi ma'lumotlarni kiritishingiz kerak</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% if can_update %}
                <form action="{% url 'filling_info' %}" method="POST"> {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name">Ism</label>
                                <input name="name" type="text" class="form-control" id="name" placeholder="Ismingiz" required>
                            </div>
                            <div class="form-group">
                                <label for="last_name">Familiya</label>
                                <input name="last_name" type="text" class="form-control" id="last_name" placeholder="Familyangiz" required>
                            </div>
                            <div class="form-group">
                                <label for="father_name">Otangizning ismi</label>
                                <input name="father_name" type="text" class="form-control" id="father_name" placeholder="Otangizning ismi" required>
                            </div>
                            <div class="form-group">
                                <label for="phone_number">Telefon raqam</label>
                                <input name="phone_number" type="text" class="form-control" id="phone_number" placeholder="Telefon raqamingiz" required>
                            </div>
                            <label for="id_job">Kasb:</label>
                            <select id="id_job" name="job" class="form-select" required>
                                {% for job in job_list %}
                                    <option value="{{ job.id }}">{{ job.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="under_age_children_number">Voyaga yetmagan farzandlarinigz soni</label>
                                <input name="under_age_children_number" type="number" class="form-control" id="under_age_children_number" placeholder="Voyaga yetmagan farzandlarinigz soni" required>
                            </div>
                            <div class="form-group">
                                <label for="adress">Manzil</label>
                                <input name="adress" type="text" class="form-control" id="adress" placeholder="Manzil" required>
                            </div>
                            <div class="form-group">
                                <label for="born_in">Tug'ilgan kuningiz</label>
                                <input name="born_in" type="date" class="form-control" id="born_in" placeholder="Tug'ilgan kuningiz" required>
                            </div>
                            <div class="form-group">
                                <label for="employment_at">Ishga kirgan sanangiz</label>
                                <input name="employment_at" type="date" class="form-control" id="employment_at" placeholder="Ishga kirgan sanangiz" required>
                            </div>
                            <div class="form-group">
                                <label for="salary">Oylik maosh</label>
                                <input name="salary" type="number" class="form-control" id="salary" placeholder="Oylik maosh" required>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Saqlash</button>
                </form>
                {% else %}
                <h2>Siz allaqachon ma'lumotlaringizni topshirgansiz ular tasdiqlanishini kutib turing !</h2>
                <a class="btn btn-primary" href="{% url 'profile' %}">Yangilash</a>
                {% endif %}
            </div>
        </div>
    </div>
  </div>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
  <script>
      // Auto-open modal when the page loads
      document.addEventListener('DOMContentLoaded', function () {
          var myModal = new bootstrap.Modal(document.getElementById('exampleModal'));
          myModal.show();
      });
  </script>
{% endblock content %}